feat: 環境変数で設定されたGSuiteドメインでしかログインできないようにする
bibliotheca-app/bibliotheca-pwa pull request #138
Opened 2019-11-10 17:28 UTC by watiko

これはあくまで UI 的な話で、権限は rules の方でしっかり設定しておく必要がある

2019-11-10 17:47 UTC, watiko commented
@sisisin 念のため確認お願いします

2019-11-11 15:14 UTC, sisisin requested changes

2019-11-11 15:14 UTC, sisisin commented on .circleci/config.yml
> +      REACT_APP_GSUITE_DOMAIN: opt.ne.jp
firebase authはgsuite以外のプロバイダも対応しているので `ALLOWED_DOMAIN` ぐらいにしておいたほうが妥当そう

2019-11-11 16:03 UTC, watiko commented on .circleci/config.yml
> +      REACT_APP_GSUITE_DOMAIN: opt.ne.jp
Done

2019-11-11 16:20 UTC, sisisin approved these changes
iei

2019-11-11 16:20 UTC, merged