Feat/deleted book collection[wip]
bibliotheca-app/bibliotheca-pwa pull request #142
Opened 2019-11-15 08:22 UTC by sisisin

2019-11-16 12:58 UTC, watiko requested changes
typo 以外は良さそう

2019-11-16 12:58 UTC, watiko commented on packages/shared/src/repositories/BookRepositoryForBatch.ts
> +  addBookToChach = async (book: BookEntry) => {
```suggestion
  addBookToCache = async (book: BookEntry) => {
```

2019-11-16 12:58 UTC, watiko commented on packages/shared/src/repositories/DeletedBookRepository.ts
> +      tx.delete(bookRef);
メモ: ここで削除しているけど、 `deletedBooks` の onCreate とかで拾ってそこで実際の削除をするようにすれば削除の際に誰が操作したか付きで通知することもできる。

2019-11-16 20:46 UTC, watiko approved these changes

2019-11-26 16:58 UTC, sisisin commented
まーーじだ

2019-11-26 16:58 UTC, merged